In [7]:
import pandas as pd
from pathlib import Path

# ---------------------------------------------------------
# 1. File paths
# ---------------------------------------------------------

input_file = Path(
    r"C:\ProgramData\MySQL\MySQL Server 8.0\Uploads\WDICSV.csv"
)

output_file = Path(
    r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Prepared.csv"
)

# ---------------------------------------------------------
# 2. Selected indicators
# ---------------------------------------------------------

selected_indicators = [
    "IT.NET.USER.ZS",      # Individuals using the Internet (% of population)
    "IT.CEL.SETS.P2",      # Mobile cellular subscriptions (per 100 people)
    "IT.NET.BBND.P2",      # Fixed broadband subscriptions (per 100 people)
    "IT.NET.SECR.P6"       # Secure Internet servers (per 1 million people)
]

# ---------------------------------------------------------
# 3. Years
# ---------------------------------------------------------

years = [str(year) for year in range(2000, 2026)]

columns_to_keep = [
    "Country Name",
    "Country Code",
    "Indicator Name",
    "Indicator Code"
] + years

# ---------------------------------------------------------
# 4. Process the large WDI file in chunks
# ---------------------------------------------------------

chunk_size = 50000
processed_chunks = []

print("Starting WDI processing...")

for i, chunk in enumerate(
    pd.read_csv(
        input_file,
        usecols=columns_to_keep,
        chunksize=chunk_size,
        low_memory=False
    )
):
    
    # Keep only the four selected indicators
    chunk = chunk[
        chunk["Indicator Code"].isin(selected_indicators)
    ].copy()
    
    if chunk.empty:
        continue
    
    # Convert wide format to long format
    chunk = chunk.melt(
        id_vars=[
            "Country Name",
            "Country Code",
            "Indicator Name",
            "Indicator Code"
        ],
        value_vars=years,
        var_name="Year",
        value_name="Value"
    )
    
    processed_chunks.append(chunk)
    
    print(f"Processed chunk {i + 1}")

# ---------------------------------------------------------
# 5. Combine processed chunks
# ---------------------------------------------------------

df = pd.concat(processed_chunks, ignore_index=True)

# ---------------------------------------------------------
# 6. Clean values
# ---------------------------------------------------------

df["Year"] = pd.to_numeric(df["Year"], errors="coerce")

df["Value"] = pd.to_numeric(
    df["Value"],
    errors="coerce"
)

# Remove missing indicator values
df = df.dropna(subset=["Value"])

# ---------------------------------------------------------
# 7. Sort the dataset
# ---------------------------------------------------------

df = df.sort_values(
    ["Country Name", "Indicator Code", "Year"]
).reset_index(drop=True)

# ---------------------------------------------------------
# 8. Save the processed dataset
# ---------------------------------------------------------

df.to_csv(
    output_file,
    index=False
)

# ---------------------------------------------------------
# 9. Display results
# ---------------------------------------------------------

print("\nProcessing complete!")
print(f"Rows: {len(df):,}")
print(f"Columns: {len(df.columns)}")
print(f"Output file: {output_file}")

display(df.head(10))

Starting WDI processing...
Processed chunk 1
Processed chunk 2
Processed chunk 3
Processed chunk 4
Processed chunk 5
Processed chunk 6
Processed chunk 7
Processed chunk 8

Processing complete!
Rows: 20,899
Columns: 6
Output file: C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Prepared.csv

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value
0,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2000,0.000000
1,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2001,0.000000
2,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2002,0.116942
3,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2003,0.879776
4,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2004,2.546619
5,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2005,4.917112
6,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2006,9.913297
7,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2007,18.016683
8,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2008,29.826763
9,Afghanistan,AFG,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2009,38.228943

In [8]:
from pathlib import Path

dataset_folder = Path(
    r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets"
)

# Find all CSV files in the dataset folder and subfolders
csv_files = list(dataset_folder.rglob("*.csv"))

for file in csv_files:
    print(file)

C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\Continent_Lookup.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\covid_country_dim.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\covid_fact_table.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\DimDate.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\netflix_titles.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\OnlineRetail.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\OnlineRetailCleaned.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\sales_data_sample.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\time_series_covid19_confirmed_global.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\time_series_covid19_deaths_global.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\time_series_covid19_recovered_global.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\UID_ISO_FIPS_LookUp_Table.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDIcountry-series.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDICountry.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDICSV.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDIfootnote.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDIseries-time.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDISeries.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Clean.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Final.csv
C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Prepared.csv

In [9]:
country_file = Path(
    r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDICountry.csv"
)

countries = pd.read_csv(country_file)

print("Rows:", len(countries))
print("Columns:", len(countries.columns))

print("\nRegion values:")
print(countries["Region"].value_counts(dropna=False))

display(
    countries[
        ["Country Code", "Short Name", "Region", "Income Group"]
    ].head(20)
)

Rows: 264
Columns: 31

Region values:
Region
Europe & Central Asia         58
Sub-Saharan Africa            48
NaN                           47
Latin America & Caribbean     42
East Asia & Pacific           37
Middle East & North Africa    23
South Asia                     6
North America                  3
Name: count, dtype: int64

,Country Code,Short Name,Region,Income Group
0,ABW,Aruba,Latin America & Caribbean,High income
1,AFE,Africa Eastern and Southern,NaN,NaN
2,AFG,Afghanistan,Middle East & North Africa,Low income
3,AFW,Africa Western and Central,NaN,NaN
4,AGO,Angola,Sub-Saharan Africa,Lower middle income
5,ALB,Albania,Europe & Central Asia,Upper middle income
6,AND,Andorra,Europe & Central Asia,High income
7,ARB,Arab World,NaN,NaN
8,ARE,United Arab Emirates,Middle East & North Africa,High income
9,ARG,Argentina,Latin America & Caribbean,Upper middle income
10,ARM,Armenia,Europe & Central Asia,Upper middle income
11,ASM,American Samoa,East Asia & Pacific,High income
12,ATG,Antigua and Barbuda,Latin America & Caribbean,High income
13,AUS,Australia,East Asia & Pacific,High income
14,AUT,Austria,Europe & Central Asia,High income
15,AZE,Azerbaijan,Europe & Central Asia,Upper middle income
16,BDI,Burundi,Sub-Saharan Africa,Low income
17,BEL,Belgium,Europe & Central Asia,High income
18,BEN,Benin,Sub-Saharan Africa,Lower middle income
19,BFA,Burkina Faso,Sub-Saharan Africa,Low income

In [8]:
# ---------------------------------------------------------
# STEP 4: Identify the African countries
# ---------------------------------------------------------
# The World Bank places Sub-Saharan African countries under
# "Sub-Saharan Africa", while Egypt is classified under
# "Middle East & North Africa".
#
# We therefore use:
#   1. All countries in Sub-Saharan Africa
#   2. Egypt, which is geographically in Africa
#
# We do NOT include the other MENA countries because they
# are geographically outside Africa.
# ---------------------------------------------------------

# Get all Sub-Saharan African countries
ssa_countries = countries[
    countries["Region"] == "Sub-Saharan Africa"
].copy()

# Add Egypt separately because it is classified as MENA
# by the World Bank but is geographically an African country.
egypt = countries[
    countries["Country Code"] == "EGY"
].copy()

# Combine the two groups
africa_countries = pd.concat(
    [ssa_countries, egypt],
    ignore_index=True
)

# Keep only the fields we need for our project
africa_countries = africa_countries[
    [
        "Country Code",
        "Short Name",
        "Region",
        "Income Group"
    ]
].copy()

# Rename columns to make them easier to understand
africa_countries = africa_countries.rename(
    columns={
        "Short Name": "Country"
    }
)

# Remove any accidental duplicate country codes
africa_countries = africa_countries.drop_duplicates(
    subset="Country Code"
)

# Standardize Country names
africa_countries["Country"] = africa_countries["Country"].replace(
    {"Egypt, Arab Republic of": "Egypt",
     "Congo, Republic of": "Rep. Congo",
     "Congo, Democratic Republic of" : "Dem. Rep. Congo",
     "Somalia, Fed. Rep." : "Somalia",
     "Gambia, The" : "Gambia"}
)

# Sort alphabetically
africa_countries = africa_countries.sort_values(
    "Country"
).reset_index(drop=True)

# Show the result
print(f"Number of African countries identified: {len(africa_countries)}")

display(africa_countries)

Number of African countries identified: 49

,Country Code,Country,Region,Income Group
0,AGO,Angola,Sub-Saharan Africa,Lower middle income
1,BEN,Benin,Sub-Saharan Africa,Lower middle income
2,BWA,Botswana,Sub-Saharan Africa,Upper middle income
3,BFA,Burkina Faso,Sub-Saharan Africa,Low income
4,BDI,Burundi,Sub-Saharan Africa,Low income
5,CPV,Cabo Verde,Sub-Saharan Africa,Upper middle income
6,CMR,Cameroon,Sub-Saharan Africa,Lower middle income
7,CAF,Central African Republic,Sub-Saharan Africa,Low income
8,TCD,Chad,Sub-Saharan Africa,Low income
9,COM,Comoros,Sub-Saharan Africa,Lower middle income
10,CIV,Côte d'Ivoire,Sub-Saharan Africa,Lower middle income
11,COD,Dem. Rep. Congo,Sub-Saharan Africa,Low income
12,EGY,Egypt,Middle East & North Africa,Lower middle income
13,GNQ,Equatorial Guinea,Sub-Saharan Africa,Upper middle income
14,ERI,Eritrea,Sub-Saharan Africa,Low income
15,SWZ,Eswatini,Sub-Saharan Africa,Lower middle income
16,ETH,Ethiopia,Sub-Saharan Africa,Low income
17,GAB,Gabon,Sub-Saharan Africa,Upper middle income
18,GMB,Gambia,Sub-Saharan Africa,Low income
19,GHA,Ghana,Sub-Saharan Africa,Lower middle income
20,GIN,Guinea,Sub-Saharan Africa,Lower middle income
21,GNB,Guinea-Bissau,Sub-Saharan Africa,Low income
22,KEN,Kenya,Sub-Saharan Africa,Lower middle income
23,LSO,Lesotho,Sub-Saharan Africa,Lower middle income
24,LBR,Liberia,Sub-Saharan Africa,Low income
25,MDG,Madagascar,Sub-Saharan Africa,Low income
26,MWI,Malawi,Sub-Saharan Africa,Low income
27,MLI,Mali,Sub-Saharan Africa,Low income
28,MRT,Mauritania,Sub-Saharan Africa,Lower middle income
29,MUS,Mauritius,Sub-Saharan Africa,Upper middle income
30,MOZ,Mozambique,Sub-Saharan Africa,Low income
31,NAM,Namibia,Sub-Saharan Africa,Lower middle income
32,NER,Niger,Sub-Saharan Africa,Low income
33,NGA,Nigeria,Sub-Saharan Africa,Lower middle income
34,COG,Rep. Congo,Sub-Saharan Africa,Lower middle income
35,RWA,Rwanda,Sub-Saharan Africa,Low income
36,SEN,Senegal,Sub-Saharan Africa,Lower middle income
37,SYC,Seychelles,Sub-Saharan Africa,High income
38,SLE,Sierra Leone,Sub-Saharan Africa,Low income
39,SOM,Somalia,Sub-Saharan Africa,Low income
40,ZAF,South Africa,Sub-Saharan Africa,Upper middle income
41,SSD,South Sudan,Sub-Saharan Africa,Low income
42,SDN,Sudan,Sub-Saharan Africa,Low income
43,STP,São Tomé and Principe,Sub-Saharan Africa,Lower middle income
44,TZA,Tanzania,Sub-Saharan Africa,Lower middle income
45,TGO,Togo,Sub-Saharan Africa,Lower middle income
46,UGA,Uganda,Sub-Saharan Africa,Low income
47,ZMB,Zambia,Sub-Saharan Africa,Lower middle income
48,ZWE,Zimbabwe,Sub-Saharan Africa,Lower middle income

In [13]:
# ---------------------------------------------------------
# STEP 5: Load and filter the technology dataset
# ---------------------------------------------------------
# Our previous Python process converted the original WDI
# wide-format dataset into a long-format dataset.
#
# Now we:
#   1. Load that prepared dataset
#   2. Keep only our 49 African countries
#   3. Add country metadata such as income group
#   4. Validate the resulting dataset
#
# We join using Country Code because it is a reliable
# identifier and avoids problems caused by country names.
# ---------------------------------------------------------

# Path to the technology dataset we created earlier
technology_file = Path(
    r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Prepared.csv"
)

# Load the prepared technology data
technology = pd.read_csv(technology_file)

print("Technology dataset loaded successfully.")
print(f"Rows: {len(technology):,}")
print(f"Columns: {len(technology.columns)}")

# ---------------------------------------------------------
# Check the columns before we continue
# ---------------------------------------------------------

print("\nColumns:")
print(technology.columns.tolist())

# ---------------------------------------------------------
# Filter the technology data using our African country list
# ---------------------------------------------------------
# Only country codes appearing in africa_countries
# will be retained.
# ---------------------------------------------------------

africa_technology = technology[
    technology["Country Code"].isin(
        africa_countries["Country Code"]
    )
].copy()

print(
    f"\nRows after filtering to African countries: "
    f"{len(africa_technology):,}"
)

# ---------------------------------------------------------
# Add country metadata
# ---------------------------------------------------------
# This gives us useful dimensions for later analysis:
#   Country
#   Region
#   Income Group
# ---------------------------------------------------------

africa_technology = africa_technology.merge(
    africa_countries,
    on="Country Code",
    how="left"
)

# ---------------------------------------------------------
# Check whether every technology record matched a country
# ---------------------------------------------------------

unmatched = africa_technology[
    africa_technology["Country"].isna()
]

print(
    f"\nUnmatched records after country join: "
    f"{len(unmatched):,}"
)

# ---------------------------------------------------------
# Display the first few records
# ---------------------------------------------------------

display(africa_technology.head(10))

# ---------------------------------------------------------
# Basic validation
# ---------------------------------------------------------

print("\nUnique African countries in dataset:")
print(africa_technology["Country"].nunique())

print("\nIndicators:")
print(
    africa_technology[
        ["Indicator Code", "Indicator Name"]
    ].drop_duplicates().to_string(index=False)
)

print("\nYear range:")
print(
    africa_technology["Year"].min(),
    "to",
    africa_technology["Year"].max()
)

Technology dataset loaded successfully.
Rows: 20,899
Columns: 6

Columns:
['Country Name', 'Country Code', 'Indicator Name', 'Indicator Code', 'Year', 'Value']

Rows after filtering to African countries: 3,975

Unmatched records after country join: 0

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value,Country,Region,Income Group
0,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2000,0.159347,Angola,Sub-Saharan Africa,Lower middle income
1,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2001,0.447836,Angola,Sub-Saharan Africa,Lower middle income
2,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2002,0.807955,Angola,Sub-Saharan Africa,Lower middle income
3,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2003,1.950544,Angola,Sub-Saharan Africa,Lower middle income
4,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2004,3.978404,Angola,Sub-Saharan Africa,Lower middle income
5,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2005,8.351587,Angola,Sub-Saharan Africa,Lower middle income
6,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2006,15.261441,Angola,Sub-Saharan Africa,Lower middle income
7,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2007,23.878150,Angola,Sub-Saharan Africa,Lower middle income
8,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2008,31.389148,Angola,Sub-Saharan Africa,Lower middle income
9,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2009,36.178912,Angola,Sub-Saharan Africa,Lower middle income

Unique African countries in dataset:
49

Indicators:
Indicator Code                                   Indicator Name
IT.CEL.SETS.P2   Mobile cellular subscriptions (per 100 people)
IT.NET.BBND.P2   Fixed broadband subscriptions (per 100 people)
IT.NET.SECR.P6   Secure Internet servers (per 1 million people)
IT.NET.USER.ZS Individuals using the Internet (% of population)

Year range:
2000 to 2024

In [14]:
# ---------------------------------------------------------
# CHECK 2025 DATA AVAILABILITY
# ---------------------------------------------------------
# We want to know whether 2025 actually contains values
# for our four selected indicators in the African countries.
# ---------------------------------------------------------

print("2025 records:")
display(
    africa_technology[
        africa_technology["Year"] == 2025
    ]
)

print(
    "\nNumber of non-missing 2025 records:",
    africa_technology[
        africa_technology["Year"] == 2025
    ]["Value"].notna().sum()
)

# ---------------------------------------------------------
# CHECK THE LATEST AVAILABLE YEAR FOR EACH INDICATOR
# ---------------------------------------------------------
# Different WDI indicators may have different data coverage.
# This tells us exactly how far each indicator currently goes.
# ---------------------------------------------------------

latest_year_by_indicator = (
    africa_technology
    .groupby(
        ["Indicator Code", "Indicator Name"]
    )["Year"]
    .max()
    .reset_index()
    .sort_values("Indicator Code")
)

display(latest_year_by_indicator)

2025 records:

Empty DataFrame
Columns: [Country Name, Country Code, Indicator Name, Indicator Code, Year, Value, Country, Region, Income Group]
Index: []

Number of non-missing 2025 records: 0

   Indicator Code                                    Indicator Name  Year
0  IT.CEL.SETS.P2    Mobile cellular subscriptions (per 100 people)  2024
1  IT.NET.BBND.P2    Fixed broadband subscriptions (per 100 people)  2024
2  IT.NET.SECR.P6    Secure Internet servers (per 1 million people)  2024
3  IT.NET.USER.ZS  Individuals using the Internet (% of population)  2024

In [15]:
# ---------------------------------------------------------
# STEP 6: DATA COVERAGE AND MISSINGNESS CHECK
# ---------------------------------------------------------
# Before analysing trends or ranking countries, we need to
# understand how complete our data is.
#
# This check helps us identify:
#   - How many observations each indicator has
#   - The available year range for each indicator
#   - How many countries have data for each indicator
#   - Which indicators have the most missing data
# ---------------------------------------------------------

# ---------------------------------------------------------
# 1. Overall coverage by indicator
# ---------------------------------------------------------
# This tells us how many records we have for each indicator
# and the first and last available year.
# ---------------------------------------------------------

indicator_coverage = (
    africa_technology
    .groupby(
        ["Indicator Code", "Indicator Name"]
    )
    .agg(
        Records=("Value", "count"),
        Countries=("Country Code", "nunique"),
        First_Year=("Year", "min"),
        Last_Year=("Year", "max")
    )
    .reset_index()
)

print("Coverage by indicator:")
display(indicator_coverage)


# ---------------------------------------------------------
# 2. Number of observations by country
# ---------------------------------------------------------
# This helps us identify countries with unusually limited
# data coverage.
# ---------------------------------------------------------

country_coverage = (
    africa_technology
    .groupby(
        ["Country Code", "Country"]
    )
    .agg(
        Records=("Value", "count"),
        Indicators=("Indicator Code", "nunique"),
        First_Year=("Year", "min"),
        Last_Year=("Year", "max")
    )
    .reset_index()
    .sort_values("Records")
)

print("\nCountry-level coverage:")
display(country_coverage)


# ---------------------------------------------------------
# 3. Check how many countries have each indicator
# ---------------------------------------------------------
# Ideally, we want to know whether all 49 countries appear
# for each indicator.
# ---------------------------------------------------------

country_indicator_coverage = (
    africa_technology
    .groupby("Indicator Code")["Country Code"]
    .nunique()
    .reset_index(name="Countries_With_Data")
)

print("\nCountries with data for each indicator:")
display(country_indicator_coverage)


# ---------------------------------------------------------
# 4. Check for duplicate records
# ---------------------------------------------------------
# A country + indicator + year combination should represent
# one observation.
#
# Duplicate records could distort our analysis, so we check
# for them before continuing.
# ---------------------------------------------------------

duplicates = (
    africa_technology
    .groupby(
        ["Country Code", "Indicator Code", "Year"]
    )
    .size()
    .reset_index(name="Count")
)

duplicates = duplicates[
    duplicates["Count"] > 1
]

print(
    f"\nDuplicate Country + Indicator + Year records: "
    f"{len(duplicates)}"
)

if len(duplicates) > 0:
    display(duplicates.head(20))

Coverage by indicator:

,Indicator Code,Indicator Name,Records,Countries,First_Year,Last_Year
0,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),1186,49,2000,2024
1,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),894,49,2000,2024
2,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),721,49,2010,2024
3,IT.NET.USER.ZS,Individuals using the Internet (% of population),1174,49,2000,2024

Country-level coverage:

,Country Code,Country,Records,Indicators,First_Year,Last_Year
38,SSD,South Sudan,44,4,2010,2024
36,SLE,Sierra Leone,62,4,2000,2024
34,SDN,Sudan,65,4,2000,2024
5,CAF,Central African Republic,67,4,2000,2024
13,ERI,Eritrea,67,4,2000,2024
37,SOM,Somalia,72,4,2000,2024
9,COG,Republic of Congo,74,4,2000,2024
17,GIN,Guinea,76,4,2000,2024
19,GNB,Guinea-Bissau,76,4,2000,2024
22,LBR,Liberia,76,4,2000,2024
8,COD,Democratic Republic of the Congo,77,4,2000,2024
25,MLI,Mali,79,4,2000,2024
1,BDI,Burundi,80,4,2000,2024
20,GNQ,Equatorial Guinea,81,4,2000,2024
42,TCD,Chad,81,4,2000,2024
24,MDG,Madagascar,82,4,2000,2024
10,COM,Comoros,82,4,2000,2024
31,NER,Niger,82,4,2000,2024
40,SWZ,Eswatini,82,4,2000,2024
32,NGA,Nigeria,83,4,2000,2024
43,TGO,Togo,83,4,2000,2024
7,CMR,Cameroon,83,4,2000,2024
45,UGA,Uganda,83,4,2000,2024
39,STP,São Tomé and Principe,84,4,2000,2024
26,MOZ,Mozambique,84,4,2000,2024
0,AGO,Angola,84,4,2000,2024
4,BWA,Botswana,84,4,2000,2024
27,MRT,Mauritania,85,4,2000,2024
30,NAM,Namibia,85,4,2000,2024
6,CIV,Côte d'Ivoire,85,4,2000,2024
18,GMB,"Gambia, The",85,4,2000,2024
23,LSO,Lesotho,85,4,2000,2024
21,KEN,Kenya,85,4,2000,2024
14,ETH,Ethiopia,85,4,2000,2024
41,SYC,Seychelles,85,4,2000,2024
33,RWA,Rwanda,85,4,2000,2024
44,TZA,Tanzania,85,4,2000,2024
29,MWI,Malawi,86,4,2000,2024
16,GHA,Ghana,86,4,2000,2024
11,CPV,Cabo Verde,86,4,2000,2024
15,GAB,Gabon,87,4,2000,2024
3,BFA,Burkina Faso,88,4,2000,2024
2,BEN,Benin,88,4,2000,2024
12,EGY,Egypt,88,4,2000,2024
28,MUS,Mauritius,88,4,2000,2024
35,SEN,Senegal,88,4,2000,2024
46,ZAF,South Africa,88,4,2000,2024
48,ZWE,Zimbabwe,89,4,2000,2024
47,ZMB,Zambia,90,4,2000,2024

Countries with data for each indicator:

   Indicator Code  Countries_With_Data
0  IT.CEL.SETS.P2                   49
1  IT.NET.BBND.P2                   49
2  IT.NET.SECR.P6                   49
3  IT.NET.USER.ZS                   49

Duplicate Country + Indicator + Year records: 0

In [16]:
# ---------------------------------------------------------
# STEP 7: IDENTIFY MISSING YEARS
# ---------------------------------------------------------
# We know that all 49 countries have all four indicators.
# However, some countries have fewer yearly observations.
#
# This step identifies:
#   1. How many observations each country has for each
#      indicator
#   2. Which years are missing
#   3. Whether missingness is concentrated in particular
#      indicators or countries
# ---------------------------------------------------------

# ---------------------------------------------------------
# Create a country-indicator coverage table
# ---------------------------------------------------------
# Each row represents one country and one indicator.
# "Years_Available" tells us how many years contain data.
# ---------------------------------------------------------

coverage_detail = (
    africa_technology
    .groupby(
        [
            "Country Code",
            "Country",
            "Indicator Code"
        ]
    )
    .agg(
        Years_Available=("Year", "nunique"),
        First_Year=("Year", "min"),
        Last_Year=("Year", "max")
    )
    .reset_index()
)

# Add the indicator name for easier reading
indicator_names = (
    africa_technology[
        ["Indicator Code", "Indicator Name"]
    ]
    .drop_duplicates()
)

coverage_detail = coverage_detail.merge(
    indicator_names,
    on="Indicator Code",
    how="left"
)

# Put the columns in a logical order
coverage_detail = coverage_detail[
    [
        "Country Code",
        "Country",
        "Indicator Code",
        "Indicator Name",
        "Years_Available",
        "First_Year",
        "Last_Year"
    ]
]

print("Country + Indicator coverage:")
display(coverage_detail)


# ---------------------------------------------------------
# Find the countries with the lowest data coverage
# ---------------------------------------------------------
# This helps us identify countries that may require
# additional caution during trend analysis.
# ---------------------------------------------------------

lowest_coverage = (
    coverage_detail
    .sort_values(
        ["Years_Available", "Country"]
    )
)

print("\nLowest country-indicator coverage:")
display(lowest_coverage.head(20))


# ---------------------------------------------------------
# Count observations by year and indicator
# ---------------------------------------------------------
# This shows how many countries have data in each year.
#
# If the number suddenly falls in a particular year,
# we know that year has incomplete country coverage.
# ---------------------------------------------------------

year_coverage = (
    africa_technology
    .groupby(
        ["Indicator Code", "Year"]
    )
    .agg(
        Countries_With_Data=("Country Code", "nunique")
    )
    .reset_index()
)

# Add indicator names
year_coverage = year_coverage.merge(
    indicator_names,
    on="Indicator Code",
    how="left"
)

year_coverage = year_coverage[
    [
        "Indicator Code",
        "Indicator Name",
        "Year",
        "Countries_With_Data"
    ]
]

print("\nCountry coverage by year:")
display(year_coverage)

Country + Indicator coverage:

,Country Code,Country,Indicator Code,Indicator Name,Years_Available,First_Year,Last_Year
0,AGO,Angola,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),25,2000,2024
1,AGO,Angola,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),19,2006,2024
2,AGO,Angola,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),15,2010,2024
3,AGO,Angola,IT.NET.USER.ZS,Individuals using the Internet (% of population),25,2000,2024
4,BDI,Burundi,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),24,2000,2023
...,...,...,...,...,...,...,...
191,ZMB,Zambia,IT.NET.USER.ZS,Individuals using the Internet (% of population),25,2000,2024
192,ZWE,Zimbabwe,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),25,2000,2024
193,ZWE,Zimbabwe,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),24,2001,2024
194,ZWE,Zimbabwe,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),15,2010,2024
195,ZWE,Zimbabwe,IT.NET.USER.ZS,Individuals using the Internet (% of population),25,2000,2024

Lowest country-indicator coverage:

,Country Code,Country,Indicator Code,Indicator Name,Years_Available,First_Year,Last_Year
145,SLE,Sierra Leone,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),3,2019,2021
155,SSD,South Sudan,IT.NET.USER.ZS,Individuals using the Internet (% of population),8,2012,2019
21,CAF,Central African Republic,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),9,2011,2022
37,COG,Republic of Congo,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),9,2009,2023
139,SDN,Sudan,IT.NET.USER.ZS,Individuals using the Internet (% of population),9,2000,2017
154,SSD,South Sudan,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),10,2015,2024
78,GNB,Guinea-Bissau,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),11,2014,2024
149,SOM,Somalia,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),11,2012,2023
22,CAF,Central African Republic,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),12,2013,2024
33,COD,Democratic Republic of the Congo,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),13,2010,2024
69,GIN,Guinea,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),13,2010,2022
152,SSD,South Sudan,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),13,2010,2023
153,SSD,South Sudan,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),13,2010,2023
53,ERI,Eritrea,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),14,2008,2022
54,ERI,Eritrea,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),14,2010,2024
89,LBR,Liberia,IT.NET.BBND.P2,Fixed broadband subscriptions (per 100 people),14,2008,2022
146,SLE,Sierra Leone,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),14,2010,2024
2,AGO,Angola,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),15,2010,2024
10,BEN,Benin,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),15,2010,2024
18,BWA,Botswana,IT.NET.SECR.P6,Secure Internet servers (per 1 million people),15,2010,2024

Country coverage by year:

,Indicator Code,Indicator Name,Year,Countries_With_Data
0,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),2000,48
1,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),2001,48
2,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),2002,48
3,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),2003,48
4,IT.CEL.SETS.P2,Mobile cellular subscriptions (per 100 people),2004,47
...,...,...,...,...
85,IT.NET.USER.ZS,Individuals using the Internet (% of population),2020,46
86,IT.NET.USER.ZS,Individuals using the Internet (% of population),2021,45
87,IT.NET.USER.ZS,Individuals using the Internet (% of population),2022,46
88,IT.NET.USER.ZS,Individuals using the Internet (% of population),2023,45
89,IT.NET.USER.ZS,Individuals using the Internet (% of population),2024,46

In [17]:
# ============================================================
# FINAL WDI TECHNOLOGY DATASET
# AFRICA-ONLY + COUNTRY INFORMATION
# ============================================================
# Goal:
# Create the final clean dataset that we will use in Power BI.
#
# The final dataset should contain:
# - Only African countries
# - 4 technology indicators
# - Available years and values
# - Country information
# - Region
# - Income Group
#
# Expected result:
# Approximately 3,975 rows
# ============================================================


import pandas as pd


# ------------------------------------------------------------
# 1. FILE PATHS
# ------------------------------------------------------------
# We are using:
#
# 1. The cleaned long-format technology dataset
# 2. The country lookup table containing Region and Income Group
#
# The original WDI data remains untouched.
# ------------------------------------------------------------

technology_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Prepared.csv"

country_lookup_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDICountry.csv"


# ------------------------------------------------------------
# 2. LOAD THE TECHNOLOGY DATA
# ------------------------------------------------------------
# This file contains the WDI technology indicators in
# long format:
#
# Country | Indicator | Year | Value
#
# Long format is easier to analyse in Power BI.
# ------------------------------------------------------------

technology = pd.read_csv(technology_path)

print("Technology dataset loaded.")
print(f"Rows: {len(technology):,}")
print(f"Columns: {len(technology.columns)}")
print()


# ------------------------------------------------------------
# 3. LOAD THE COUNTRY LOOKUP
# ------------------------------------------------------------
# WDICountry contains information about countries including
# their region and income classification.
# ------------------------------------------------------------

countries = pd.read_csv(country_lookup_path)

print("Country lookup loaded.")
print(f"Rows: {len(countries):,}")
print(f"Columns: {len(countries.columns)}")
print()


# ------------------------------------------------------------
# 4. CHECK THE COUNTRY LOOKUP COLUMNS
# ------------------------------------------------------------
# We need to identify the exact columns containing:
# - Country Code
# - Short Name
# - Region
# - Income Group
#
# This check prevents us from guessing column names.
# ------------------------------------------------------------

print("Country lookup columns:")
print(countries.columns.tolist())
print()


# ------------------------------------------------------------
# 5. KEEP ONLY THE COUNTRY INFORMATION WE NEED
# ------------------------------------------------------------
# We only need these four columns from the country lookup.
# ------------------------------------------------------------

country_info = countries[
    ["Country Code", "Short Name", "Region", "Income Group"]
].copy()


# ------------------------------------------------------------
# 6. FILTER TO AFRICAN COUNTRIES
# ------------------------------------------------------------
# The World Bank region field identifies Sub-Saharan Africa,
# but North Africa is classified under Middle East &
# North Africa.
#
# Therefore, we cannot simply filter Region =
# "Sub-Saharan Africa".
#
# Instead, we use our verified list of 49 African country
# codes from the Africa country lookup we created earlier.
# ------------------------------------------------------------

africa_codes = [
    "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR",
    "CAF", "TCD", "COM", "COD", "COG", "CIV", "EGY",
    "GNQ", "ERI", "SWZ", "ETH", "GAB", "GMB", "GHA",
    "GIN", "GNB", "KEN", "LSO", "LBR", "MDG", "MWI",
    "MLI", "MRT", "MUS", "MOZ", "NAM", "NER", "NGA",
    "RWA", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD",
    "SDN", "STP", "TZA", "TGO", "UGA", "ZMB", "ZWE"
]

print(f"African country codes defined: {len(africa_codes)}")
print()


# ------------------------------------------------------------
# 7. FILTER THE TECHNOLOGY DATA TO AFRICAN COUNTRIES
# ------------------------------------------------------------
# Only observations belonging to our 49 African countries
# should remain in the final analytical dataset.
# ------------------------------------------------------------

africa_technology = technology[
    technology["Country Code"].isin(africa_codes)
].copy()

print("After filtering to African countries:")
print(f"Rows: {len(africa_technology):,}")
print(f"Unique countries: {africa_technology['Country Code'].nunique()}")
print()


# ------------------------------------------------------------
# 8. JOIN COUNTRY INFORMATION
# ------------------------------------------------------------
# We now attach:
# - Country name
# - Region
# - Income Group
#
# Country Code is used as the matching key because it is a
# standardized identifier and is more reliable than country
# names.
# ------------------------------------------------------------

final_df = africa_technology.merge(
    country_info,
    on="Country Code",
    how="left"
)


# ------------------------------------------------------------
# 9. REMOVE THE DUPLICATE COUNTRY NAME COLUMN
# ------------------------------------------------------------
# The technology dataset already has "Country Name".
# The lookup has "Short Name".
#
# We don't need both, so we remove the lookup's duplicate
# country-name field.
# ------------------------------------------------------------

final_df = final_df.drop(columns=["Short Name"])


# ------------------------------------------------------------
# 10. CHECK THE JOIN
# ------------------------------------------------------------
# If Region or Income Group is missing, it means a country
# could not be matched to the lookup table.
#
# We expect zero unmatched records.
# ------------------------------------------------------------

missing_region = final_df["Region"].isna().sum()
missing_income = final_df["Income Group"].isna().sum()

print("Join validation:")
print(f"Missing Region: {missing_region}")
print(f"Missing Income Group: {missing_income}")
print()


# ------------------------------------------------------------
# 11. CHECK FOR DUPLICATES
# ------------------------------------------------------------
# A country should have only one observation for each
# indicator and year.
#
# For example:
# Angola + Mobile subscriptions + 2020
#
# should appear only once.
# ------------------------------------------------------------

duplicates = final_df.duplicated(
    subset=["Country Code", "Indicator Code", "Year"]
).sum()

print(f"Duplicate Country + Indicator + Year records: {duplicates}")
print()


# ------------------------------------------------------------
# 12. CHECK THE YEAR RANGE
# ------------------------------------------------------------
# We are checking the actual years that contain observations.
#
# Remember:
# Missing years are NOT automatically zeros.
# They simply mean the World Bank did not provide an
# observation for that country/indicator/year.
# ------------------------------------------------------------

print(f"Earliest year: {final_df['Year'].min()}")
print(f"Latest year: {final_df['Year'].max()}")
print()


# ------------------------------------------------------------
# 13. CHECK INDICATORS
# ------------------------------------------------------------
# Confirm that our four technology indicators are present.
# ------------------------------------------------------------

print("Indicators:")
print(
    final_df[
        ["Indicator Code", "Indicator Name"]
    ].drop_duplicates().to_string(index=False)
)
print()


# ------------------------------------------------------------
# 14. FINAL DATASET SUMMARY
# ------------------------------------------------------------

print("============================================================")
print("FINAL DATASET SUMMARY")
print("============================================================")

print(f"Rows:              {len(final_df):,}")
print(f"Columns:           {len(final_df.columns)}")
print(f"Countries:         {final_df['Country Code'].nunique()}")
print(f"Indicators:        {final_df['Indicator Code'].nunique()}")
print(f"Year range:        {final_df['Year'].min()}–{final_df['Year'].max()}")
print(f"Duplicates:        {duplicates}")
print(f"Missing Region:    {missing_region}")
print(f"Missing Income:    {missing_income}")

print("============================================================")
print()


# ------------------------------------------------------------
# 15. DISPLAY THE FINAL DATASET
# ------------------------------------------------------------
# Looking at the first few rows helps us visually confirm
# that everything looks correct before saving the file.
# ------------------------------------------------------------

display(final_df.head(10))


# ------------------------------------------------------------
# 16. SAVE THE FINAL DATASET
# ------------------------------------------------------------
# This is the file we will eventually import into Power BI.
#
# We are deliberately giving it a new name so we don't
# accidentally overwrite the previous intermediate file.
# ------------------------------------------------------------

output_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Final.csv"

final_df.to_csv(
    output_path,
    index=False
)

print()
print("============================================================")
print("FINAL DATASET SAVED SUCCESSFULLY")
print("============================================================")
print(f"Output file: {output_path}")

Technology dataset loaded.
Rows: 20,899
Columns: 6

Country lookup loaded.
Rows: 264
Columns: 31

Country lookup columns:
['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code', 'National accounts base year', 'National accounts reference year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'Alternative conversion factor', 'PPP survey year', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census', 'Latest household survey', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data']

African country codes defined: 49

After filtering to African countries:
Rows: 3,975
Unique countries: 49

Join validation:
Missing Region: 0
Missing Income Group: 0

Duplicate Country + Indicator + Year records: 0

Earliest year: 2000
Latest year: 2024

Indicators:
Indicator Code                                   Indicator Name
IT.CEL.SETS.P2   Mobile cellular subscriptions (per 100 people)
IT.NET.BBND.P2   Fixed broadband subscriptions (per 100 people)
IT.NET.SECR.P6   Secure Internet servers (per 1 million people)
IT.NET.USER.ZS Individuals using the Internet (% of population)

============================================================
FINAL DATASET SUMMARY
============================================================
Rows:              3,975
Columns:           8
Countries:         49
Indicators:        4
Year range:        2000–2024
Duplicates:        0
Missing Region:    0
Missing Income:    0
============================================================

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value,Region,Income Group
0,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2000,0.159347,Sub-Saharan Africa,Lower middle income
1,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2001,0.447836,Sub-Saharan Africa,Lower middle income
2,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2002,0.807955,Sub-Saharan Africa,Lower middle income
3,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2003,1.950544,Sub-Saharan Africa,Lower middle income
4,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2004,3.978404,Sub-Saharan Africa,Lower middle income
5,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2005,8.351587,Sub-Saharan Africa,Lower middle income
6,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2006,15.261441,Sub-Saharan Africa,Lower middle income
7,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2007,23.878150,Sub-Saharan Africa,Lower middle income
8,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2008,31.389148,Sub-Saharan Africa,Lower middle income
9,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2009,36.178912,Sub-Saharan Africa,Lower middle income

============================================================
FINAL DATASET SAVED SUCCESSFULLY
============================================================
Output file: C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Final.csv

In [1]:
# ============================================================
# FINAL WDI TECHNOLOGY DATASET
# AFRICA-ONLY + COUNTRY INFORMATION
# ============================================================
# Goal:
# Create the final clean dataset that we will use in Power BI.
#
# The final dataset should contain:
# - Only African countries
# - 4 technology indicators
# - Available years and values
# - Country information
# - Region
# - Income Group
#
# Expected result:
# Approximately 3,975 rows
# ============================================================


import pandas as pd


# ------------------------------------------------------------
# 1. FILE PATHS
# ------------------------------------------------------------
# We are using:
#
# 1. The cleaned long-format technology dataset
# 2. The country lookup table containing Region and Income Group
#
# The original WDI data remains untouched.
# ------------------------------------------------------------

technology_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Prepared.csv"

country_lookup_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDICountry.csv"


# ------------------------------------------------------------
# 2. LOAD THE TECHNOLOGY DATA
# ------------------------------------------------------------
# This file contains the WDI technology indicators in
# long format:
#
# Country | Indicator | Year | Value
#
# Long format is easier to analyse in Power BI.
# ------------------------------------------------------------

technology = pd.read_csv(technology_path)

print("Technology dataset loaded.")
print(f"Rows: {len(technology):,}")
print(f"Columns: {len(technology.columns)}")
print()


# ------------------------------------------------------------
# 3. LOAD THE COUNTRY LOOKUP
# ------------------------------------------------------------
# WDICountry contains information about countries including
# their region and income classification.
# ------------------------------------------------------------

countries = pd.read_csv(country_lookup_path)

print("Country lookup loaded.")
print(f"Rows: {len(countries):,}")
print(f"Columns: {len(countries.columns)}")
print()


# ------------------------------------------------------------
# 4. CHECK THE COUNTRY LOOKUP COLUMNS
# ------------------------------------------------------------
# We need to identify the exact columns containing:
# - Country Code
# - Short Name
# - Region
# - Income Group
#
# This check prevents us from guessing column names.
# ------------------------------------------------------------

print("Country lookup columns:")
print(countries.columns.tolist())
print()


# ------------------------------------------------------------
# 5. KEEP ONLY THE COUNTRY INFORMATION WE NEED
# ------------------------------------------------------------
# We only need these four columns from the country lookup.
# ------------------------------------------------------------

country_info = countries[
    ["Country Code", "Short Name", "Region", "Income Group"]
].copy()


# ------------------------------------------------------------
# 6. FILTER TO AFRICAN COUNTRIES
# ------------------------------------------------------------
# The World Bank region field identifies Sub-Saharan Africa,
# but North Africa is classified under Middle East &
# North Africa.
#
# Therefore, we cannot simply filter Region =
# "Sub-Saharan Africa".
#
# Instead, we use our verified list of 49 African country
# codes from the Africa country lookup we created earlier.
# ------------------------------------------------------------

africa_codes = [
    "AGO", "BEN", "BWA", "BFA", "BDI", "CPV", "CMR",
    "CAF", "TCD", "COM", "COD", "COG", "CIV", "EGY",
    "GNQ", "ERI", "SWZ", "ETH", "GAB", "GMB", "GHA",
    "GIN", "GNB", "KEN", "LSO", "LBR", "MDG", "MWI",
    "MLI", "MRT", "MUS", "MOZ", "NAM", "NER", "NGA",
    "RWA", "SEN", "SYC", "SLE", "SOM", "ZAF", "SSD",
    "SDN", "STP", "TZA", "TGO", "UGA", "ZMB", "ZWE"
]

print(f"African country codes defined: {len(africa_codes)}")
print()


# ------------------------------------------------------------
# 7. FILTER THE TECHNOLOGY DATA TO AFRICAN COUNTRIES
# ------------------------------------------------------------
# Only observations belonging to our 49 African countries
# should remain in the final analytical dataset.
# ------------------------------------------------------------

africa_technology = technology[
    technology["Country Code"].isin(africa_codes)
].copy()

print("After filtering to African countries:")
print(f"Rows: {len(africa_technology):,}")
print(f"Unique countries: {africa_technology['Country Code'].nunique()}")
print()


# ------------------------------------------------------------
# 8. JOIN COUNTRY INFORMATION
# ------------------------------------------------------------
# We now attach:
# - Country name
# - Region
# - Income Group
#
# Country Code is used as the matching key because it is a
# standardized identifier and is more reliable than country
# names.
# ------------------------------------------------------------

final_df = africa_technology.merge(
    country_info,
    on="Country Code",
    how="left"
)


# ------------------------------------------------------------
# 9. REMOVE THE DUPLICATE COUNTRY NAME COLUMN
# ------------------------------------------------------------
# The technology dataset already has "Country Name".
# The lookup has "Short Name".
#
# We don't need both, so we remove the lookup's duplicate
# country-name field.
# ------------------------------------------------------------

final_df = final_df.drop(columns=["Short Name"])


# ------------------------------------------------------------
# 10. CHECK THE JOIN
# ------------------------------------------------------------
# If Region or Income Group is missing, it means a country
# could not be matched to the lookup table.
#
# We expect zero unmatched records.
# ------------------------------------------------------------

missing_region = final_df["Region"].isna().sum()
missing_income = final_df["Income Group"].isna().sum()

print("Join validation:")
print(f"Missing Region: {missing_region}")
print(f"Missing Income Group: {missing_income}")
print()


# ------------------------------------------------------------
# 11. CHECK FOR DUPLICATES
# ------------------------------------------------------------
# A country should have only one observation for each
# indicator and year.
#
# For example:
# Angola + Mobile subscriptions + 2020
#
# should appear only once.
# ------------------------------------------------------------

duplicates = final_df.duplicated(
    subset=["Country Code", "Indicator Code", "Year"]
).sum()

print(f"Duplicate Country + Indicator + Year records: {duplicates}")
print()


# ------------------------------------------------------------
# 14. FINAL STANDARDIZATION
# ------------------------------------------------------------
final_df["Country Name"] = final_df["Country Name"].replace(
    {"Egypt, Arab Rep.": "Egypt",
     "Congo, Rep.": "Rep. Congo",
     "Congo, Dem. Rep." : "Dem. Rep. Congo",
     "Somalia, Fed. Rep." : "Somalia",
     "Gambia, The" : "Gambia"}
)

# ------------------------------------------------------------
# 12. CHECK THE YEAR RANGE
# ------------------------------------------------------------
# We are checking the actual years that contain observations.
#
# Remember:
# Missing years are NOT automatically zeros.
# They simply mean the World Bank did not provide an
# observation for that country/indicator/year.
# ------------------------------------------------------------

print(f"Earliest year: {final_df['Year'].min()}")
print(f"Latest year: {final_df['Year'].max()}")
print()


# ------------------------------------------------------------
# 13. CHECK INDICATORS
# ------------------------------------------------------------
# Confirm that our four technology indicators are present.
# ------------------------------------------------------------

print("Indicators:")
print(
    final_df[
        ["Indicator Code", "Indicator Name"]
    ].drop_duplicates().to_string(index=False)
)
print()


# ------------------------------------------------------------
# 14. FINAL DATASET SUMMARY
# ------------------------------------------------------------

print("============================================================")
print("FINAL DATASET SUMMARY")
print("============================================================")

print(f"Rows:              {len(final_df):,}")
print(f"Columns:           {len(final_df.columns)}")
print(f"Countries:         {final_df['Country Code'].nunique()}")
print(f"Indicators:        {final_df['Indicator Code'].nunique()}")
print(f"Year range:        {final_df['Year'].min()}–{final_df['Year'].max()}")
print(f"Duplicates:        {duplicates}")
print(f"Missing Region:    {missing_region}")
print(f"Missing Income:    {missing_income}")

print("============================================================")
print()


# ------------------------------------------------------------
# 15. DISPLAY THE FINAL DATASET
# ------------------------------------------------------------
# Looking at the first few rows helps us visually confirm
# that everything looks correct before saving the file.
# ------------------------------------------------------------

display(final_df.head(10))


# ------------------------------------------------------------
# 16. SAVE THE FINAL DATASET
# ------------------------------------------------------------
# This is the file we will eventually import into Power BI.
#
# We are deliberately giving it a new name so we don't
# accidentally overwrite the previous intermediate file.
# ------------------------------------------------------------

output_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Final.csv"

final_df.to_csv(
    output_path,
    index=False
)

print()
print("============================================================")
print("FINAL DATASET SAVED SUCCESSFULLY")
print("============================================================")
print(f"Output file: {output_path}")

Technology dataset loaded.
Rows: 20,899
Columns: 6

Country lookup loaded.
Rows: 264
Columns: 31

Country lookup columns:
['Country Code', 'Short Name', 'Table Name', 'Long Name', '2-alpha code', 'Currency Unit', 'Special Notes', 'Region', 'Income Group', 'WB-2 code', 'National accounts base year', 'National accounts reference year', 'SNA price valuation', 'Lending category', 'Other groups', 'System of National Accounts', 'Alternative conversion factor', 'PPP survey year', 'Balance of Payments Manual in use', 'External debt Reporting status', 'System of trade', 'Government Accounting concept', 'IMF data dissemination standard', 'Latest population census', 'Latest household survey', 'Source of most recent Income and expenditure data', 'Vital registration complete', 'Latest agricultural census', 'Latest industrial data', 'Latest trade data', 'Latest water withdrawal data']

African country codes defined: 49

After filtering to African countries:
Rows: 3,975
Unique countries: 49

Join validation:
Missing Region: 0
Missing Income Group: 0

Duplicate Country + Indicator + Year records: 0

Earliest year: 2000
Latest year: 2024

Indicators:
Indicator Code                                   Indicator Name
IT.CEL.SETS.P2   Mobile cellular subscriptions (per 100 people)
IT.NET.BBND.P2   Fixed broadband subscriptions (per 100 people)
IT.NET.SECR.P6   Secure Internet servers (per 1 million people)
IT.NET.USER.ZS Individuals using the Internet (% of population)

============================================================
FINAL DATASET SUMMARY
============================================================
Rows:              3,975
Columns:           8
Countries:         49
Indicators:        4
Year range:        2000–2024
Duplicates:        0
Missing Region:    0
Missing Income:    0
============================================================

,Country Name,Country Code,Indicator Name,Indicator Code,Year,Value,Region,Income Group
0,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2000,0.159347,Sub-Saharan Africa,Lower middle income
1,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2001,0.447836,Sub-Saharan Africa,Lower middle income
2,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2002,0.807955,Sub-Saharan Africa,Lower middle income
3,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2003,1.950544,Sub-Saharan Africa,Lower middle income
4,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2004,3.978404,Sub-Saharan Africa,Lower middle income
5,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2005,8.351587,Sub-Saharan Africa,Lower middle income
6,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2006,15.261441,Sub-Saharan Africa,Lower middle income
7,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2007,23.878150,Sub-Saharan Africa,Lower middle income
8,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2008,31.389148,Sub-Saharan Africa,Lower middle income
9,Angola,AGO,Mobile cellular subscriptions (per 100 people),IT.CEL.SETS.P2,2009,36.178912,Sub-Saharan Africa,Lower middle income

============================================================
FINAL DATASET SAVED SUCCESSFULLY
============================================================
Output file: C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDI_Technology_Africa_Final.csv

In [2]:
# ============================================================
# WDI SERIES METADATA
# Purpose:
# Load the World Bank indicator metadata so we can understand
# exactly what our indicator codes mean and how they are defined.
# ============================================================

import pandas as pd

# ------------------------------------------------------------
# 1. Define the file paths
# These are the raw WDI metadata files that came with the
# World Bank WDI download.
# ------------------------------------------------------------

wdi_series_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDISeries.csv"

wdi_series_time_path = r"C:\Users\pc\OneDrive\Documents\Data Analytics Projects\AnalystLab Africa Internship\Datasets\WDIseries-time.csv"


# ------------------------------------------------------------
# 2. Load the WDI Series file
#
# This file describes the indicators themselves.
# We want to understand:
# - Indicator codes
# - Indicator names
# - Definitions
# - Units
# - Sources
# - Other metadata
# ------------------------------------------------------------

wdi_series = pd.read_csv(
    wdi_series_path,
    encoding="latin1"
)

print("WDI Series loaded successfully.")
print(f"Rows: {len(wdi_series):,}")
print(f"Columns: {len(wdi_series.columns)}")
print()


# ------------------------------------------------------------
# 3. Inspect the columns
# ------------------------------------------------------------

print("WDI Series columns:")
print(wdi_series.columns.tolist())
print()


# ------------------------------------------------------------
# 4. Preview the data
# ------------------------------------------------------------

print("First 5 rows:")
display(wdi_series.head())


# ============================================================
# WDI SERIES-TIME
# Purpose:
# Check the metadata that describes the time coverage or
# availability of the WDI indicators.
# ============================================================

# ------------------------------------------------------------
# 5. Load the WDI Series-Time file
# ------------------------------------------------------------

wdi_series_time = pd.read_csv(
    wdi_series_time_path,
    encoding="latin1"
)

print("\nWDI Series-Time loaded successfully.")
print(f"Rows: {len(wdi_series_time):,}")
print(f"Columns: {len(wdi_series_time.columns)}")
print()


# ------------------------------------------------------------
# 6. Inspect the columns
# ------------------------------------------------------------

print("WDI Series-Time columns:")
print(wdi_series_time.columns.tolist())
print()


# ------------------------------------------------------------
# 7. Preview the data
# ------------------------------------------------------------

print("First 5 rows:")
display(wdi_series_time.head())

WDI Series loaded successfully.
Rows: 1,498
Columns: 20

WDI Series columns:
['ï»¿Series Code', 'Topic', 'Indicator Name', 'Short definition', 'Long definition', 'Unit of measure', 'Periodicity', 'Base Period', 'Other notes', 'Aggregation method', 'Limitations and exceptions', 'Notes from original source', 'General comments', 'Source', 'Statistical concept and methodology', 'Development relevance', 'Related source links', 'Other web links', 'Related indicators', 'License Type']

First 5 rows:

,ï»¿Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Base Period,Other notes,Aggregation method,Limitations and exceptions,Notes from original source,General comments,Source,Statistical concept and methodology,Development relevance,Related source links,Other web links,Related indicators,License Type
0,AG.CON.FERT.PT.ZS,Environment: Agricultural production,Fertilizer consumption (% of fertilizer produc...,NaN,Fertilizer consumption measures the quantity o...,% (ratio),Annual,NaN,The world and regional aggregate series do not...,Weighted average,The FAO has revised the time series for fertil...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Fertilizer consumption measures t...,"Factors, such as the green revolution, have le...",NaN,NaN,NaN,CC BY-4.0
1,AG.CON.FERT.ZS,Environment: Agricultural production,Fertilizer consumption (kilograms per hectare ...,NaN,Fertilizer consumption measures the quantity o...,kg per hectare of arable land,Annual,NaN,The world and regional aggregate series do not...,Weighted average,The FAO has revised the time series for fertil...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Fertilizer consumption measures t...,"Factors, such as the green revolution, have le...",NaN,NaN,NaN,CC BY-4.0
2,AG.LND.AGRI.K2,Environment: Land use,Agricultural land (sq. km),NaN,Agricultural land refers to the land area that...,square kilometers (sq. km),Annual,NaN,Areas of former states are included in the suc...,Sum,The data are collected by the Food and Agricul...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Agricultural land constitutes onl...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0
3,AG.LND.AGRI.ZS,Environment: Land use,Agricultural land (% of land area),NaN,Agricultural land refers to the share of land ...,% (share) of land area,Annual,NaN,Areas of former states are included in the suc...,Weighted average,The data are collected by the Food and Agricul...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Agriculture is still a major sect...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0
4,AG.LND.ARBL.HA,Environment: Land use,Arable land (hectares),NaN,Arable land (in hectares) includes land define...,hectares,Annual,NaN,Areas of former states are included in the suc...,NaN,The Food and Agriculture Organization (FAO) tr...,NaN,NaN,"FAO electronic files and web site, Food and Ag...",Methodology: Temporary fallow land refers to l...,Agricultural land covers more than one-third o...,NaN,NaN,NaN,CC BY-4.0

WDI Series-Time loaded successfully.
Rows: 143
Columns: 3

WDI Series-Time columns:
['ï»¿SeriesCode', 'Year', 'DESCRIPTION']

First 5 rows:

    ï»¿SeriesCode    Year                                        DESCRIPTION
0     SP.UWT.TFRT  YR1990  Averages for regions/groups are based on count...
1  SP.REG.DTHS.ZS  YR1990  Averages for regions/groups are based on count...
2     SP.DYN.WFRT  YR1990  Averages for regions/groups are based on count...
3  SP.DYN.CONU.ZS  YR1990  Averages for regions/groups are based on count...
4  SH.FPL.SATM.ZS  YR1990  Averages for regions/groups are based on count...

In [3]:
# ============================================================
# FIX AND CLEAN WDI METADATA COLUMN NAMES
# ============================================================
#
# Purpose:
# The WDI files contain a BOM at the beginning of the first
# column name. In our file it appears as "ï»¿".
#
# We will remove it from the column names so we can work with
# the metadata normally.
# ============================================================


# ------------------------------------------------------------
# 1. Remove the visible BOM characters from column names
# ------------------------------------------------------------

wdi_series.columns = (
    wdi_series.columns
    .str.replace("ï»¿", "", regex=False)
    .str.strip()
)

wdi_series_time.columns = (
    wdi_series_time.columns
    .str.replace("ï»¿", "", regex=False)
    .str.strip()
)


# ------------------------------------------------------------
# 2. Check that the column names are now correct
# ------------------------------------------------------------

print("WDI Series columns:")
print(wdi_series.columns.tolist())

print("\nWDI Series-Time columns:")
print(wdi_series_time.columns.tolist())


# ============================================================
# VERIFY OUR FOUR INDICATORS
# ============================================================
#
# Purpose:
# Confirm the official World Bank metadata for the four
# indicators used in our project.
# ============================================================


our_indicators = [
    "IT.CEL.SETS.P2",   # Mobile cellular subscriptions
    "IT.NET.BBND.P2",   # Fixed broadband subscriptions
    "IT.NET.SECR.P6",   # Secure Internet servers
    "IT.NET.USER.ZS"    # Individuals using the Internet
]


# ------------------------------------------------------------
# 3. Find our four indicators in the metadata
# ------------------------------------------------------------

indicator_check = wdi_series[
    wdi_series["Series Code"].isin(our_indicators)
].copy()


# ------------------------------------------------------------
# 4. Select the metadata that is relevant to our analysis
# ------------------------------------------------------------

columns_to_show = [
    "Series Code",
    "Topic",
    "Indicator Name",
    "Short definition",
    "Long definition",
    "Unit of measure",
    "Periodicity",
    "Aggregation method",
    "Limitations and exceptions"
]


# ------------------------------------------------------------
# 5. Display the results
# ------------------------------------------------------------

print("\nOur four indicators found in WDI Series:")
print(f"Indicators found: {len(indicator_check)}")

display(indicator_check[columns_to_show])

WDI Series columns:
['Series Code', 'Topic', 'Indicator Name', 'Short definition', 'Long definition', 'Unit of measure', 'Periodicity', 'Base Period', 'Other notes', 'Aggregation method', 'Limitations and exceptions', 'Notes from original source', 'General comments', 'Source', 'Statistical concept and methodology', 'Development relevance', 'Related source links', 'Other web links', 'Related indicators', 'License Type']

WDI Series-Time columns:
['SeriesCode', 'Year', 'DESCRIPTION']

Our four indicators found in WDI Series:
Indicators found: 4

,Series Code,Topic,Indicator Name,Short definition,Long definition,Unit of measure,Periodicity,Aggregation method,Limitations and exceptions
553,IT.CEL.SETS.P2,Infrastructure: Communications,Mobile cellular subscriptions (per 100 people),NaN,Mobile cellular telephone subscriptions are su...,number of subscriptions*100/population,Annual,Weighted average,Operators have traditionally been the main sou...
557,IT.NET.BBND.P2,Infrastructure: Communications,Fixed broadband subscriptions (per 100 people),NaN,Fixed broadband subscriptions refers to fixed ...,number of subscriptions*100/population,Annual,Weighted average,Data are collected by national statistics offi...
559,IT.NET.SECR.P6,Infrastructure: Communications,Secure Internet servers (per 1 million people),NaN,"The number of distinct, publicly-trusted TLS/S...",Count,Annual,Weighted average,Netcraft only visits sites on the standard HTT...
562,IT.NET.USER.ZS,Infrastructure: Communications,Individuals using the Internet (% of population),NaN,Internet users are individuals who have used t...,% of population,Annual,Weighted average,Operators have traditionally been the main sou...

In [4]:
# ============================================================
# CHECK WDI SERIES-TIME FOR OUR FOUR INDICATORS
# ============================================================
#
# Purpose:
# WDI Series-Time contains additional notes about specific
# indicator/year combinations.
#
# We want to check whether there are any important notes
# affecting the interpretation of our four indicators.
# ============================================================


# ------------------------------------------------------------
# 1. Find records belonging to our four indicators
# ------------------------------------------------------------

series_time_check = wdi_series_time[
    wdi_series_time["SeriesCode"].isin(our_indicators)
].copy()


# ------------------------------------------------------------
# 2. Display the results
# ------------------------------------------------------------

print("WDI Series-Time records for our four indicators:")
print(f"Records found: {len(series_time_check)}")

display(series_time_check)

WDI Series-Time records for our four indicators:
Records found: 0

Empty DataFrame
Columns: [SeriesCode, Year, DESCRIPTION]
Index: []